In [1]:
import tensorflow as tf
import numpy as np

In [2]:
train_1d = tf.Variable([1,2,3,4,5,6,7,8,9])
train_1d.shape

TensorShape([9])

In [3]:
train_2d = tf.Variable([[1,2,3],[4,5,6],[7,8,9]])
train_2d.shape

TensorShape([3, 3])

In [4]:
train_3d = tf.Variable([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])
train_3d.shape

TensorShape([3, 3, 3])

In [5]:
labels = tf.constant([1,2,3])

#Prova reshape

In [6]:
train = tf.zeros([3,3,3])
train

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [7]:
reshapeL = tf.keras.layers.Reshape([9])
a = reshapeL(train)
print(a)
print(train)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(3, 9), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(3, 3, 3), dtype=float32)


In [8]:
t1 = [[1, 2, 3],
      [4, 5, 6]]

t2 = tf.reshape(t1, [6])
t2

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [9]:
#Tring with a model
model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(3,1), name= "IIIIIII"),
    #tf.keras.layers.Reshape([9]),
    tf.keras.layers.Dense(3),
    tf.keras.layers.Dense(1)
])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3, 3)              6         
                                                                 
 dense_1 (Dense)             (None, 3, 1)              4         
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [10]:
print(model.input.shape)
print(model.output.shape)

(None, 3, 1)
(None, 3, 1)


In [11]:
#Tring with a model
model_2 = tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(10,1), name= "IIIIIII"),
    #tf.keras.layers.Reshape([9]),
    tf.keras.layers.LSTM(25),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Lambda(lambda x: tf.expand_dims(x, axis=-1)),
    tf.keras.layers.Dense(1)
])
model_2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 25)                2700      
                                                                 
 dense_2 (Dense)             (None, 10)                260       
                                                                 
 lambda (Lambda)             (None, 10, 1)             0         
                                                                 
 dense_3 (Dense)             (None, 10, 1)             2         
                                                                 
Total params: 2,962
Trainable params: 2,962
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model_2.input.shape)
print(model_2.output.shape)

(None, 10, 1)
(None, 10, 1)


In [13]:
prova = np.zeros((18,10,1))
for i in range(18):
  print(i)
prova[:,:,0] = np.arange(0,10)
#prova

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


In [14]:
def normalize_series(data, min, max):
    data = data - min
    data = data / max
    return data

In [15]:
def make_fake_windows(BATCH_SIZE,N_PAST,N_FUTURE):
  tot_series = np.random.randint(low = 1, high = 10, size=BATCH_SIZE * (N_PAST+N_FUTURE))
  tot_series = normalize_series(tot_series, np.amin(tot_series), np.amax(tot_series))
  window_step = np.expand_dims(np.arange(N_PAST+N_FUTURE), axis=0)
  window_indexes = window_step + np.expand_dims(np.arange(len(tot_series)-(N_PAST+N_FUTURE-1)), axis=0).T # create 2D array of windows of size window_size
  tot_series = tot_series[window_indexes]
  features = tot_series[:,:N_PAST]
  labels = tot_series[:,N_PAST:]
  return (np.expand_dims(features, axis=-1),np.expand_dims(labels, axis=-1))
  

In [21]:
(features,labels)  = make_fake_windows(50,10,10)
print(labels.shape)
#print(labels)
print(features.shape)
#print(features)

(981, 10, 1)
(981, 10, 1)


In [17]:
features = np.zeros((18,10,1))
labels = prova
print(features.shape,labels.shape)

(18, 10, 1) (18, 10, 1)


In [ ]:
model_2.compile(tf.optimizers.Adam(), loss='mae')
model_2.fit(features,
          labels,
          epochs=100)

In [19]:
model_2.evaluate(features)

1/1 [==============================] - 1s 621ms/step - loss: 0.0000e+00


0.0

In [20]:
np.reshape(labels,(13,3))

ValueError: ignored

In [ ]:
np.reshape(features,(13,3))

In [ ]:
pred = model_2.predict(features)
np.reshape(pred,(981,10))[:10,:]

In [ ]:
pred.shape , labels.shape

In [ ]:
tf.keras.metrics.mean_absolute_error(labels, pred).numpy()

In [ ]:
l = np.zeros((10,10))
p = np.ones((10,10))
tf.keras.metrics.mean_absolute_error(l,p).numpy()

In [ ]:
l = np.zeros((32,10,1))
l[:,:,0] = np.arange(10)
#print(l)
l[15 -10:-1,0,0]